// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Tue Feb 23 16:36:05 2021

jh_adc_rfsig jh_adc_rfsig_inst
(
	.CLOCK_65(CLOCK_65_sig) ,	// input  CLOCK_65_sig
	.rst(rst_sig) ,	// input  rst_sig
	.start_write(start_write_sig) ,	// input  start_write_sig
	.monitor_ADC(monitor_ADC_sig) ,	// input [13:0] monitor_ADC_sig
	.sram_readdata(sram_readdata_sig) ,	// input [15:0] sram_readdata_sig
	.sram_writedata(sram_writedata_sig) ,	// output [15:0] sram_writedata_sig
	.sram_address(sram_address_sig) ,	// output [6:0] sram_address_sig
	.sram_write(sram_write_sig) ,	// output  sram_write_sig
	.min_voltage(min_voltage_sig) ,	// output [15:0] min_voltage_sig
	.max_voltage(max_voltage_sig) ,	// output [15:0] max_voltage_sig
	.Vpp(Vpp_sig) 	// output [15:0] Vpp_sig
);

