	nios2 u0 (
		.adc_ltc2308_0_conduit_end_CONVST             (<connected-to-adc_ltc2308_0_conduit_end_CONVST>),             //             adc_ltc2308_0_conduit_end.CONVST
		.adc_ltc2308_0_conduit_end_SCK                (<connected-to-adc_ltc2308_0_conduit_end_SCK>),                //                                      .SCK
		.adc_ltc2308_0_conduit_end_SDI                (<connected-to-adc_ltc2308_0_conduit_end_SDI>),                //                                      .SDI
		.adc_ltc2308_0_conduit_end_SDO                (<connected-to-adc_ltc2308_0_conduit_end_SDO>),                //                                      .SDO
		.bridge_0_external_interface_address          (<connected-to-bridge_0_external_interface_address>),          //           bridge_0_external_interface.address
		.bridge_0_external_interface_byte_enable      (<connected-to-bridge_0_external_interface_byte_enable>),      //                                      .byte_enable
		.bridge_0_external_interface_read             (<connected-to-bridge_0_external_interface_read>),             //                                      .read
		.bridge_0_external_interface_write            (<connected-to-bridge_0_external_interface_write>),            //                                      .write
		.bridge_0_external_interface_write_data       (<connected-to-bridge_0_external_interface_write_data>),       //                                      .write_data
		.bridge_0_external_interface_acknowledge      (<connected-to-bridge_0_external_interface_acknowledge>),      //                                      .acknowledge
		.bridge_0_external_interface_read_data        (<connected-to-bridge_0_external_interface_read_data>),        //                                      .read_data
		.clk_clk                                      (<connected-to-clk_clk>),                                      //                                   clk.clk
		.clock_bridge_0_in_clk_clk                    (<connected-to-clock_bridge_0_in_clk_clk>),                    //                 clock_bridge_0_in_clk.clk
		.clock_bridge_100_out_clk_clk                 (<connected-to-clock_bridge_100_out_clk_clk>),                 //              clock_bridge_100_out_clk.clk
		.clock_bridge_65_out_clk_clk                  (<connected-to-clock_bridge_65_out_clk_clk>),                  //               clock_bridge_65_out_clk.clk
		.command_from_hps_external_connection_export  (<connected-to-command_from_hps_external_connection_export>),  //  command_from_hps_external_connection.export
		.electrode_voltage_external_connection_export (<connected-to-electrode_voltage_external_connection_export>), // electrode_voltage_external_connection.export
		.fifo_fpga_to_hps_clk_in_clk                  (<connected-to-fifo_fpga_to_hps_clk_in_clk>),                  //               fifo_fpga_to_hps_clk_in.clk
		.fifo_fpga_to_hps_in_writedata                (<connected-to-fifo_fpga_to_hps_in_writedata>),                //                   fifo_fpga_to_hps_in.writedata
		.fifo_fpga_to_hps_in_write                    (<connected-to-fifo_fpga_to_hps_in_write>),                    //                                      .write
		.fifo_fpga_to_hps_in_csr_address              (<connected-to-fifo_fpga_to_hps_in_csr_address>),              //               fifo_fpga_to_hps_in_csr.address
		.fifo_fpga_to_hps_in_csr_read                 (<connected-to-fifo_fpga_to_hps_in_csr_read>),                 //                                      .read
		.fifo_fpga_to_hps_in_csr_writedata            (<connected-to-fifo_fpga_to_hps_in_csr_writedata>),            //                                      .writedata
		.fifo_fpga_to_hps_in_csr_write                (<connected-to-fifo_fpga_to_hps_in_csr_write>),                //                                      .write
		.fifo_fpga_to_hps_in_csr_readdata             (<connected-to-fifo_fpga_to_hps_in_csr_readdata>),             //                                      .readdata
		.fifo_fpga_to_hps_reset_in_reset_n            (<connected-to-fifo_fpga_to_hps_reset_in_reset_n>),            //             fifo_fpga_to_hps_reset_in.reset_n
		.fifo_hps_to_fpga_clk_out_clk                 (<connected-to-fifo_hps_to_fpga_clk_out_clk>),                 //              fifo_hps_to_fpga_clk_out.clk
		.fifo_hps_to_fpga_out_readdata                (<connected-to-fifo_hps_to_fpga_out_readdata>),                //                  fifo_hps_to_fpga_out.readdata
		.fifo_hps_to_fpga_out_read                    (<connected-to-fifo_hps_to_fpga_out_read>),                    //                                      .read
		.fifo_hps_to_fpga_out_csr_address             (<connected-to-fifo_hps_to_fpga_out_csr_address>),             //              fifo_hps_to_fpga_out_csr.address
		.fifo_hps_to_fpga_out_csr_read                (<connected-to-fifo_hps_to_fpga_out_csr_read>),                //                                      .read
		.fifo_hps_to_fpga_out_csr_writedata           (<connected-to-fifo_hps_to_fpga_out_csr_writedata>),           //                                      .writedata
		.fifo_hps_to_fpga_out_csr_write               (<connected-to-fifo_hps_to_fpga_out_csr_write>),               //                                      .write
		.fifo_hps_to_fpga_out_csr_readdata            (<connected-to-fifo_hps_to_fpga_out_csr_readdata>),            //                                      .readdata
		.fifo_hps_to_fpga_reset_out_reset_n           (<connected-to-fifo_hps_to_fpga_reset_out_reset_n>),           //            fifo_hps_to_fpga_reset_out.reset_n
		.finish_fdtd_external_connection_export       (<connected-to-finish_fdtd_external_connection_export>),       //       finish_fdtd_external_connection.export
		.hps_io_hps_io_emac1_inst_TX_CLK              (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),              //                                hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0                (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),                //                                      .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1                (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),                //                                      .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2                (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),                //                                      .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3                (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),                //                                      .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0                (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),                //                                      .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO                (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),                //                                      .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC                 (<connected-to-hps_io_hps_io_emac1_inst_MDC>),                 //                                      .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL              (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),              //                                      .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL              (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),              //                                      .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK              (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),              //                                      .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1                (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),                //                                      .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2                (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),                //                                      .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3                (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),                //                                      .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0                  (<connected-to-hps_io_hps_io_qspi_inst_IO0>),                  //                                      .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1                  (<connected-to-hps_io_hps_io_qspi_inst_IO1>),                  //                                      .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2                  (<connected-to-hps_io_hps_io_qspi_inst_IO2>),                  //                                      .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3                  (<connected-to-hps_io_hps_io_qspi_inst_IO3>),                  //                                      .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0                  (<connected-to-hps_io_hps_io_qspi_inst_SS0>),                  //                                      .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK                  (<connected-to-hps_io_hps_io_qspi_inst_CLK>),                  //                                      .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD                  (<connected-to-hps_io_hps_io_sdio_inst_CMD>),                  //                                      .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                   (<connected-to-hps_io_hps_io_sdio_inst_D0>),                   //                                      .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                   (<connected-to-hps_io_hps_io_sdio_inst_D1>),                   //                                      .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK                  (<connected-to-hps_io_hps_io_sdio_inst_CLK>),                  //                                      .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                   (<connected-to-hps_io_hps_io_sdio_inst_D2>),                   //                                      .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                   (<connected-to-hps_io_hps_io_sdio_inst_D3>),                   //                                      .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                   (<connected-to-hps_io_hps_io_usb1_inst_D0>),                   //                                      .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                   (<connected-to-hps_io_hps_io_usb1_inst_D1>),                   //                                      .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                   (<connected-to-hps_io_hps_io_usb1_inst_D2>),                   //                                      .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                   (<connected-to-hps_io_hps_io_usb1_inst_D3>),                   //                                      .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                   (<connected-to-hps_io_hps_io_usb1_inst_D4>),                   //                                      .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                   (<connected-to-hps_io_hps_io_usb1_inst_D5>),                   //                                      .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                   (<connected-to-hps_io_hps_io_usb1_inst_D6>),                   //                                      .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                   (<connected-to-hps_io_hps_io_usb1_inst_D7>),                   //                                      .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK                  (<connected-to-hps_io_hps_io_usb1_inst_CLK>),                  //                                      .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP                  (<connected-to-hps_io_hps_io_usb1_inst_STP>),                  //                                      .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR                  (<connected-to-hps_io_hps_io_usb1_inst_DIR>),                  //                                      .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT                  (<connected-to-hps_io_hps_io_usb1_inst_NXT>),                  //                                      .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK                 (<connected-to-hps_io_hps_io_spim1_inst_CLK>),                 //                                      .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI                (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),                //                                      .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO                (<connected-to-hps_io_hps_io_spim1_inst_MISO>),                //                                      .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0                 (<connected-to-hps_io_hps_io_spim1_inst_SS0>),                 //                                      .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX                  (<connected-to-hps_io_hps_io_uart0_inst_RX>),                  //                                      .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX                  (<connected-to-hps_io_hps_io_uart0_inst_TX>),                  //                                      .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA                  (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),                  //                                      .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL                  (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),                  //                                      .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA                  (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),                  //                                      .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL                  (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),                  //                                      .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09               (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),               //                                      .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35               (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),               //                                      .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO48               (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),               //                                      .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO53               (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),               //                                      .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54               (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),               //                                      .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61               (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),               //                                      .hps_io_gpio_inst_GPIO61
		.hw_reset_external_connection_export          (<connected-to-hw_reset_external_connection_export>),          //          hw_reset_external_connection.export
		.iteration_number_external_connection_export  (<connected-to-iteration_number_external_connection_export>),  //  iteration_number_external_connection.export
		.memory_mem_a                                 (<connected-to-memory_mem_a>),                                 //                                memory.mem_a
		.memory_mem_ba                                (<connected-to-memory_mem_ba>),                                //                                      .mem_ba
		.memory_mem_ck                                (<connected-to-memory_mem_ck>),                                //                                      .mem_ck
		.memory_mem_ck_n                              (<connected-to-memory_mem_ck_n>),                              //                                      .mem_ck_n
		.memory_mem_cke                               (<connected-to-memory_mem_cke>),                               //                                      .mem_cke
		.memory_mem_cs_n                              (<connected-to-memory_mem_cs_n>),                              //                                      .mem_cs_n
		.memory_mem_ras_n                             (<connected-to-memory_mem_ras_n>),                             //                                      .mem_ras_n
		.memory_mem_cas_n                             (<connected-to-memory_mem_cas_n>),                             //                                      .mem_cas_n
		.memory_mem_we_n                              (<connected-to-memory_mem_we_n>),                              //                                      .mem_we_n
		.memory_mem_reset_n                           (<connected-to-memory_mem_reset_n>),                           //                                      .mem_reset_n
		.memory_mem_dq                                (<connected-to-memory_mem_dq>),                                //                                      .mem_dq
		.memory_mem_dqs                               (<connected-to-memory_mem_dqs>),                               //                                      .mem_dqs
		.memory_mem_dqs_n                             (<connected-to-memory_mem_dqs_n>),                             //                                      .mem_dqs_n
		.memory_mem_odt                               (<connected-to-memory_mem_odt>),                               //                                      .mem_odt
		.memory_mem_dm                                (<connected-to-memory_mem_dm>),                                //                                      .mem_dm
		.memory_oct_rzqin                             (<connected-to-memory_oct_rzqin>),                             //                                      .oct_rzqin
		.module_csr_external_connection_export        (<connected-to-module_csr_external_connection_export>),        //        module_csr_external_connection.export
		.number32_export                              (<connected-to-number32_export>),                              //                              number32.export
		.o_pw_forward_external_connection_export      (<connected-to-o_pw_forward_external_connection_export>),      //      o_pw_forward_external_connection.export
		.o_pw_reversed_external_connection_export     (<connected-to-o_pw_reversed_external_connection_export>),     //     o_pw_reversed_external_connection.export
		.o_temperature2_external_connection_export    (<connected-to-o_temperature2_external_connection_export>),    //    o_temperature2_external_connection.export
		.o_temperature_external_connection_export     (<connected-to-o_temperature_external_connection_export>),     //     o_temperature_external_connection.export
		.onchip_ram1_reset1_reset                     (<connected-to-onchip_ram1_reset1_reset>),                     //                    onchip_ram1_reset1.reset
		.onchip_ram1_reset1_reset_req                 (<connected-to-onchip_ram1_reset1_reset_req>),                 //                                      .reset_req
		.onchip_ram1_s1_address                       (<connected-to-onchip_ram1_s1_address>),                       //                        onchip_ram1_s1.address
		.onchip_ram1_s1_clken                         (<connected-to-onchip_ram1_s1_clken>),                         //                                      .clken
		.onchip_ram1_s1_chipselect                    (<connected-to-onchip_ram1_s1_chipselect>),                    //                                      .chipselect
		.onchip_ram1_s1_write                         (<connected-to-onchip_ram1_s1_write>),                         //                                      .write
		.onchip_ram1_s1_readdata                      (<connected-to-onchip_ram1_s1_readdata>),                      //                                      .readdata
		.onchip_ram1_s1_writedata                     (<connected-to-onchip_ram1_s1_writedata>),                     //                                      .writedata
		.onchip_ram1_s1_byteenable                    (<connected-to-onchip_ram1_s1_byteenable>),                    //                                      .byteenable
		.onchip_ram2_reset1_reset                     (<connected-to-onchip_ram2_reset1_reset>),                     //                    onchip_ram2_reset1.reset
		.onchip_ram2_reset1_reset_req                 (<connected-to-onchip_ram2_reset1_reset_req>),                 //                                      .reset_req
		.onchip_ram2_s1_address                       (<connected-to-onchip_ram2_s1_address>),                       //                        onchip_ram2_s1.address
		.onchip_ram2_s1_clken                         (<connected-to-onchip_ram2_s1_clken>),                         //                                      .clken
		.onchip_ram2_s1_chipselect                    (<connected-to-onchip_ram2_s1_chipselect>),                    //                                      .chipselect
		.onchip_ram2_s1_write                         (<connected-to-onchip_ram2_s1_write>),                         //                                      .write
		.onchip_ram2_s1_readdata                      (<connected-to-onchip_ram2_s1_readdata>),                      //                                      .readdata
		.onchip_ram2_s1_writedata                     (<connected-to-onchip_ram2_s1_writedata>),                     //                                      .writedata
		.onchip_ram2_s1_byteenable                    (<connected-to-onchip_ram2_s1_byteenable>),                    //                                      .byteenable
		.pll_adc_locked_export                        (<connected-to-pll_adc_locked_export>),                        //                        pll_adc_locked.export
		.power_unlock_external_connection_export      (<connected-to-power_unlock_external_connection_export>),      //      power_unlock_external_connection.export
		.reset_reset                                  (<connected-to-reset_reset>),                                  //                                 reset.reset
		.rf_on_off_external_connection_export         (<connected-to-rf_on_off_external_connection_export>),         //         rf_on_off_external_connection.export
		.sdram_clk_clk                                (<connected-to-sdram_clk_clk>),                                //                             sdram_clk.clk
		.sdram_wire_addr                              (<connected-to-sdram_wire_addr>),                              //                            sdram_wire.addr
		.sdram_wire_ba                                (<connected-to-sdram_wire_ba>),                                //                                      .ba
		.sdram_wire_cas_n                             (<connected-to-sdram_wire_cas_n>),                             //                                      .cas_n
		.sdram_wire_cke                               (<connected-to-sdram_wire_cke>),                               //                                      .cke
		.sdram_wire_cs_n                              (<connected-to-sdram_wire_cs_n>),                              //                                      .cs_n
		.sdram_wire_dq                                (<connected-to-sdram_wire_dq>),                                //                                      .dq
		.sdram_wire_dqm                               (<connected-to-sdram_wire_dqm>),                               //                                      .dqm
		.sdram_wire_ras_n                             (<connected-to-sdram_wire_ras_n>),                             //                                      .ras_n
		.sdram_wire_we_n                              (<connected-to-sdram_wire_we_n>),                              //                                      .we_n
		.sp_external_connection_export                (<connected-to-sp_external_connection_export>),                //                sp_external_connection.export
		.sw_external_connection_export                (<connected-to-sw_external_connection_export>),                //                sw_external_connection.export
		.thermocouples_sel_external_connection_export (<connected-to-thermocouples_sel_external_connection_export>), // thermocouples_sel_external_connection.export
		.vga_out_CLK                                  (<connected-to-vga_out_CLK>),                                  //                               vga_out.CLK
		.vga_out_HS                                   (<connected-to-vga_out_HS>),                                   //                                      .HS
		.vga_out_VS                                   (<connected-to-vga_out_VS>),                                   //                                      .VS
		.vga_out_BLANK                                (<connected-to-vga_out_BLANK>),                                //                                      .BLANK
		.vga_out_SYNC                                 (<connected-to-vga_out_SYNC>),                                 //                                      .SYNC
		.vga_out_R                                    (<connected-to-vga_out_R>),                                    //                                      .R
		.vga_out_G                                    (<connected-to-vga_out_G>),                                    //                                      .G
		.vga_out_B                                    (<connected-to-vga_out_B>),                                    //                                      .B
		.vga_ref_reset_reset                          (<connected-to-vga_ref_reset_reset>),                          //                         vga_ref_reset.reset
		.video_ref_clk_clk                            (<connected-to-video_ref_clk_clk>)                             //                         video_ref_clk.clk
	);

